### ISSUE TITLE
Task For Nabeel Siddiqui 14682

### ISSUE THREAD

**Issue by nabeel-siddiqui-14682** [Fahadeez/MAD-Project#1]
**Tasks UI(User Interface)**

- [x] SignIn Page
- [x] SignUp Page
- [x] HomePage/Dashboard
- [x] Side Menu (side bar)
Items Showed:
a)image
b)username
c)category items
d)My cart
e)my orders
d)Account settings

- [x] Account Setting Page

- [x] Separate Category Product Page

@nabeel-siddiqui-14682

**Comment by nabeel-siddiqui-14682** [comment]
Done!
