### ISSUE TITLE
Tasks For Shahzaib Guahar khan 14944

### ISSUE THREAD

**Issue by nabeel-siddiqui-14682** [Fahadeez/MAD-Project#3]
**Tasks UI(User Interface)**

- [x] Category Page
**Includes:**
- [x] Each Category Page (Minimum 2-3 Category Page) of desired category

- [x] Add To Cart Page
- [x] Proceed To Payment Page
- [x] order history Page
- [x] E-Wallet/Bonus coins page
- [x] about us page

@Shahzaib-Gauhar-Khan-14944

**Comment by nabeel-siddiqui-14682** [comment]
Done
